openapi: 3.0.1
info:
  title: '@jupiterone/graph-salesforce'
  description: Salesforce integration for JupiterOne
  x-cortex-git:
    github:
      repository: JupiterOne/graph-salesforce
  x-cortex-owners:
    - type: group
      name: JupiterOne/integrations
  x-cortex-tag: '@jupiterone/graph-salesforce'
  x-cortex-service-groups:
    - tier-4
